version: '3.8'

# default configs
x-default:
  &default
  deploy:
    resources:
      limits:
        memory: 16m # defaulted memory limit to 16mb
  restart: unless-stopped

services:
  app-go:
    <<: *default
    build:
      context: ./app-go
    x-develop:
      watch:
        - action: rebuild
          path: ./app-go
    image: credits-app-go:local
    container_name: app-go 
    command: /app-go serve
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: 
      - 80:80
    environment:
      DB_CONN: host=postgres user=local password=local dbname=credit port=5432 sslmode=disable
      REDIS_URI: redis://:local@redis:6379/0
    healthcheck:
      test: [ "CMD", "/wget", "--quiet", "--output-document=-", "http://0.0.0.0:80/health" ]

  app-go-worker:
    <<: *default
    build:
      context: ./app-go
    x-develop:
      watch:
        - action: rebuild
          path: ./app-go
    image: credits-app-go:local
    container_name: app-go-worker 
    command: /app-go work
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_CONN: host=postgres user=local password=local dbname=credit port=5432 sslmode=disable
      REDIS_URI: redis://:local@redis:6379/0
    deploy:
      resources:
        limits:
          memory: 32m # override memory limit, otherwise app-go-worker will ate more cpu
 