version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: credits
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
    image: credits-api:local
    container_name: api 
    ports: 
      - 8080:8080
 
  load-test:
    build:
      context: ./load-test
    image: credits-load-test:local
    container_name: load-test
    network_mode: host
