version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: credit
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    image: credits-api:local
    restart: unless-stopped
    container_name: api 
    depends_on:
      postgres:
        condition: service_healthy
    ports: 
      - 80:80
    environment:
      DB_CONN: host=host.docker.internal user=local password=local dbname=credit port=5432 sslmode=disable
    healthcheck:
      test: wget --quiet --output-document=- http://0.0.0.0:80/health
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
 
  # load-test:
  #   build:
  #     context: ./load-test
  #   image: credits-load-test:local
  #   container_name: load-test
  #   network_mode: host

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana 
  #   ports:
  #     - "8091:3000"
  #   environment:
  #     GF_AUTH_ANONYMOUS_ENABLED: true
  #     GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  #     GF_AUTH_DISABLE_LOGIN_FORM: true
